language: node_js
node_js: 
  - "12"
cache: yarn
script:
  - "npm run lint"
  - "npm test"
  - "npm run build"
install:
  - yarn global add firebase-tools
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
branches:
  only: 
    - master